name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # create pages for docs
      - name: Create pages for docs
        run: task docs

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
