name: Setup
on: [push]

permissions: write-all

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # build names
      - name: Build names
        id: names
        run: |
          echo "repository=${REPOSITORY//$OWNER\//}" >> $GITHUB_OUTPUT
          echo "image=${REPOSITORY//$OWNER\/docker-/}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}

      # checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # setup taskfile
      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # prepare files
      - name: Setup repository
        run: task setup
        env:
          REPOSITORY_NAME: ${{ steps.names.outputs.repository }}
          IMAGE_NAME: ${{ steps.names.outputs.image }}

      # commit changes
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: feature/initialize
          title: 'chore: initialize repository'
          commit-message: 'chore: initialize repository from template'
          assignees: ${{ github.actor }}
          delete-branch: true
          sign-commits: true
          signoff: true
